# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'win1803'

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'

  - script: |
      choco install mingw
      refreshenv
    displayName: 'Install build tools'
    
  - script: dir /s c:\tools
    displayName: 'Show installed tools'

  - script: mingw32-make -j
    displayName: 'Build'
